services:
  btm-ems-3:
    image: ghcr.io/starenergyems/btm_ems_v3_frontend:latest
    ports:
      - "3000:80"
    restart: unless-stopped
    stop_signal: SIGTERM
    stop_grace_period: 10s
    networks:
      - default
      - ems-network

networks:
  ems-network:
    external: true
    name: ems-network
