export const accountDatas = {
  data: [
    {
      _id: 'SS0061',
      name: 'Yui',
      company: null,
      department: null,
      permission: '管理者',
      status: 1,
      password: '$2b$12$ldnT5k6xuMGe51Ry7r6QG.6n2UQM5X5bBWEHisIE4qy0uIeFmEG16',
      lasttime: 1768205637,
      id: 'SS0061',
      email: 'yui.cheng@starexchange-power.com',
    },
    {
      _id: 'admin',
      name: 'admin',
      company: null,
      department: null,
      status: 1,
      password: '$2b$12$eK/pnXg1j2YI8pVAj4giCewNeFoCpbL1D1AkLC9WUGfGzeubPWZHe',
      lasttime: 1768205637,
      permission: '最高權限',
      id: 'admin',
      email: 'admin@starexchange-power.com',
    },
    {
      _id: 'manager',
      name: 'manager',
      company: null,
      department: null,
      status: 1,
      password: '$2b$12$eK/pnXg1j2YI8pVAj4giCewNeFoCpbL1D1AkLC9WUGfGzeubPWZHe',
      lasttime: null,
      permission: '管理者',
      id: 'manager',
      email: 'manager@starexchange-power.com',
    },
    {
      _id: 'viewer',
      _rev: '1-e1e42907cfa2330677f67d6031e15cc9',
      name: 'viewer',
      company: null,
      department: null,
      status: 1,
      password: '$2b$12$eK/pnXg1j2YI8pVAj4giCewNeFoCpbL1D1AkLC9WUGfGzeubPWZHe',
      lasttime: null,
      permission: '一般用戶',
      id: 'viewer',
      email: 'viewer@starexchange-power.com',
    },
  ],
  status: 200,
};

export const userDatas = {
  data: {
    _id: 'SS0061',
    name: 'Yui',
    company: null,
    department: null,
    permission: '管理者',
    status: 1,
    lasttime: 1768205637,
    id: 'SS0061',
    email: 'yui.cheng@starexchange-power.com',
  },
  status: 200,
};
