export const accountDatas = {
  data: [
    {
      _id: 'SS0061',
      company: null,
      department: null,
      email: 'yui.cheng@starexchange-power.com',
      id: 'SS0061',
      lasttime: 1768205637,
      name: 'Yui',
      password: '$2b$12$ldnT5k6xuMGe51Ry7r6QG.6n2UQM5X5bBWEHisIE4qy0uIeFmEG16',
      permission: '管理者',
      status: 1,
    },
    {
      _id: 'admin',
      company: null,
      department: null,
      email: 'admin@starexchange-power.com',
      id: 'admin',
      lasttime: 1768205637,
      name: 'admin',
      password: '$2b$12$eK/pnXg1j2YI8pVAj4giCewNeFoCpbL1D1AkLC9WUGfGzeubPWZHe',
      permission: '最高權限',
      status: 1,
    },
    {
      _id: 'manager',
      company: null,
      department: null,
      email: 'manager@starexchange-power.com',
      id: 'manager',
      lasttime: null,
      name: 'manager',
      password: '$2b$12$eK/pnXg1j2YI8pVAj4giCewNeFoCpbL1D1AkLC9WUGfGzeubPWZHe',
      permission: '管理者',
      status: 1,
    },
    {
      _id: 'viewer',
      _rev: '1-e1e42907cfa2330677f67d6031e15cc9',
      company: null,
      department: null,
      email: 'viewer@starexchange-power.com',
      id: 'viewer',
      lasttime: null,
      name: 'viewer',
      password: '$2b$12$eK/pnXg1j2YI8pVAj4giCewNeFoCpbL1D1AkLC9WUGfGzeubPWZHe',
      permission: '一般用戶',
      status: 1,
    },
  ],
  status: 200,
};

export const userDatas = {
  data: {
    _id: 'SS0061',
    company: null,
    department: null,
    email: 'yui.cheng@starexchange-power.com',
    id: 'SS0061',
    lasttime: 1768205637,
    name: 'Yui',
    permission: '管理者',
    status: 1,
  },
  status: 200,
};
